print("this program will display the sum, the rest, the product, division and divsion with decimal of two given numbers")
x=(int(input("give me a number")))
y=(int(input("give me another number")))
r=int(x+y)
m=int(x*y)
p=int(x-y)
d=int(x//y)
dc=int(x/y)
print(" the sum of", x, " and", y, "is", r)
print(" the rest of", x, " and", y, "is", p)
print(" the product of", x, " and", y, "is", m)
print(" the division without decimals of", x, " and", y, "is", d)
print(" the division with decimals of", x, " and", y, "is", dc)